# Generated by Django 5.2.7 on 2025-10-17 16:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_verified",
            field=models.BooleanField(
                default=False,
                help_text="Wurde die E-Mail-Adresse verifiziert?",
                verbose_name="E-Mail verifiziert",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="email_verified_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="E-Mail verifiziert am"
            ),
        ),
        migrations.CreateModel(
            name="EmailVerificationToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="Token",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="Zeitpunkt, ab dem das Token ungültig wird",
                        verbose_name="Läuft ab am",
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Zeitpunkt der Verifizierung",
                        null=True,
                        verbose_name="Verifiziert am",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_verification_tokens",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Benutzer",
                    ),
                ),
            ],
            options={
                "verbose_name": "E-Mail-Verifizierungs-Token",
                "verbose_name_plural": "E-Mail-Verifizierungs-Tokens",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["token"], name="accounts_em_token_5f2b37_idx"),
                    models.Index(
                        fields=["user"], name="accounts_em_user_id_0b26dd_idx"
                    ),
                    models.Index(
                        fields=["expires_at"], name="accounts_em_expires_f36bd3_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PasswordResetToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="Token",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="Zeitpunkt, ab dem das Token ungültig wird",
                        verbose_name="Läuft ab am",
                    ),
                ),
                (
                    "used_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Zeitpunkt der Verwendung (NULL = noch nicht verwendet)",
                        null=True,
                        verbose_name="Verwendet am",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="password_reset_tokens",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Benutzer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Passwort-Reset-Token",
                "verbose_name_plural": "Passwort-Reset-Tokens",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["token"], name="accounts_pa_token_affdf2_idx"),
                    models.Index(
                        fields=["user"], name="accounts_pa_user_id_be3557_idx"
                    ),
                    models.Index(
                        fields=["expires_at"], name="accounts_pa_expires_01b447_idx"
                    ),
                ],
            },
        ),
    ]
