# Generated by Django 5.2.7 on 2025-10-17 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_email_verified_user_email_verified_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_login_device",
            field=models.CharField(
                blank=True,
                help_text="User-Agent des letzten Logins",
                max_length=255,
                null=True,
                verbose_name="Letztes Login-Gerät",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="last_login_ip",
            field=models.GenericIPAddressField(
                blank=True,
                help_text="IP-Adresse des letzten Logins",
                null=True,
                verbose_name="Letzte Login-IP",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="login_notifications_enabled",
            field=models.BooleanField(
                default=True,
                help_text="E-Mail-Benachrichtigungen bei Login von neuer IP/Gerät",
                verbose_name="Login-Benachrichtigungen aktiviert",
            ),
        ),
        migrations.CreateModel(
            name="UserSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        help_text="Eindeutige Session-Identifikation",
                        max_length=255,
                        unique=True,
                        verbose_name="Session-ID",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        help_text="IP-Adresse der Session", verbose_name="IP-Adresse"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        help_text="Browser/Gerät-Informationen",
                        verbose_name="User-Agent",
                    ),
                ),
                (
                    "device_name",
                    models.CharField(
                        blank=True,
                        help_text="Benutzerfreundlicher Gerätename",
                        max_length=255,
                        null=True,
                        verbose_name="Gerätename",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Ist die Session noch aktiv?",
                        verbose_name="Aktiv",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Zeitpunkt der Session-Erstellung",
                        verbose_name="Erstellt am",
                    ),
                ),
                (
                    "last_activity",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Zeitpunkt der letzten Aktivität",
                        verbose_name="Letzte Aktivität",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="Zeitpunkt des Session-Ablaufs",
                        verbose_name="Läuft ab am",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="active_sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Benutzer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Benutzer-Session",
                "verbose_name_plural": "Benutzer-Sessions",
                "ordering": ["-last_activity"],
            },
        ),
    ]
