# Generated by Django 5.2.7 on 2025-10-18 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_last_login_device_user_last_login_ip_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
