# Generated by Django 5.2.7 on 2025-10-18 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_user_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="passkeycredential",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Gibt an, ob das Credential aktiv ist",
                verbose_name="Aktiv",
            ),
        ),
    ]
