# Generated by Django 5.2.7 on 2025-10-18 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_passkeycredential_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="PasskeyAuthChallenge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("challenge", models.TextField(help_text="Base64-kodierte Challenge")),
                (
                    "expires_at",
                    models.DateTimeField(help_text="Ablaufzeit der Challenge"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "used",
                    models.BooleanField(
                        default=False,
                        help_text="Ob die Challenge bereits verwendet wurde",
                    ),
                ),
            ],
            options={
                "verbose_name": "Passkey Auth Challenge",
                "verbose_name_plural": "Passkey Auth Challenges",
                "db_table": "accounts_passkey_auth_challenge",
                "ordering": ["-created_at"],
            },
        ),
    ]
