# Generated by Django 5.2.7 on 2025-10-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_passkeyauthchallenge"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("SUPER_ADMIN", "Super-Administrator"),
                    ("ADMIN", "Administrator"),
                    ("MANAGER", "Manager"),
                    ("USER", "Benutzer"),
                    ("GUEST", "Gast"),
                ],
                default="USER",
                help_text="Rolle bestimmt die verfügbaren Funktionen im System",
                max_length=20,
                verbose_name="Benutzerrolle",
            ),
        ),
    ]
