# Generated by Django 5.0.8 on 2025-10-16 22:59

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "supplier",
                    models.CharField(max_length=100, verbose_name="Lieferant"),
                ),
                (
                    "currency",
                    models.CharField(
                        default="EUR", max_length=3, verbose_name="Währung"
                    ),
                ),
                (
                    "items_subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=10,
                        verbose_name="Zwischensumme",
                    ),
                ),
                (
                    "shipping_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=10,
                        verbose_name="Versandkosten",
                    ),
                ),
                (
                    "customs_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=10,
                        verbose_name="Zollkosten",
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=10,
                        verbose_name="Gesamtkosten",
                    ),
                ),
                ("note", models.TextField(blank=True, null=True, verbose_name="Notiz")),
                (
                    "ordered_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Bestellt am"
                    ),
                ),
                (
                    "received_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Eingegangen am"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am"),
                ),
            ],
            options={
                "verbose_name": "Bestellung",
                "verbose_name_plural": "Bestellungen",
                "ordering": ["-ordered_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[("MATERIAL", "Material"), ("OILBATCH", "Öl-Charge")],
                        max_length=20,
                        verbose_name="Zieltyp",
                    ),
                ),
                ("target_id", models.PositiveIntegerField(verbose_name="Ziel-ID")),
                (
                    "qty",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Menge",
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=4, max_digits=10, verbose_name="Einzelkosten"
                    ),
                ),
                (
                    "allocated_shipping",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=10,
                        verbose_name="Zugewiesener Versand",
                    ),
                ),
                (
                    "allocated_customs",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=10,
                        verbose_name="Zugewiesener Zoll",
                    ),
                ),
                (
                    "effective_cost_per_unit",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=10,
                        verbose_name="Effektive Kosten pro Einheit",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.order",
                        verbose_name="Bestellung",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bestellposition",
                "verbose_name_plural": "Bestellpositionen",
            },
        ),
    ]
