# Generated by Django 5.0.8 on 2025-10-16 22:59

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("materials", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ToolUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "qty_used",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Verwendete Menge",
                    ),
                ),
                (
                    "reason",
                    models.TextField(blank=True, null=True, verbose_name="Grund"),
                ),
                (
                    "used_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Verwendet am"
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        help_text="Material mit Kategorie TOOL",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tool_usages",
                        to="materials.material",
                        verbose_name="Material",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Benutzer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tool-Verbrauch",
                "verbose_name_plural": "Tool-Verbräuche",
                "ordering": ["-used_at"],
            },
        ),
    ]
