# Generated by Django 5.0.8 on 2025-10-16 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SystemSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        default="LCREE", max_length=100, verbose_name="Firmenname"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="EUR", max_length=3, verbose_name="Währung"
                    ),
                ),
                ("qr_base_url", models.URLField(verbose_name="QR-Code Basis-URL")),
                ("print_agent_url", models.URLField(verbose_name="Print-Agent URL")),
                (
                    "default_loss_factor_oil_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=2.0,
                        max_digits=5,
                        verbose_name="Standard-Verlustfaktor Öl (%)",
                    ),
                ),
                (
                    "require_second_batch_scan_on_insufficient",
                    models.BooleanField(
                        default=True,
                        verbose_name="Zweite Charge-Scan bei unzureichender Menge erforderlich",
                    ),
                ),
                (
                    "show_older_batch_warning",
                    models.BooleanField(
                        default=True,
                        verbose_name="Warnung bei älteren Chargen anzeigen",
                    ),
                ),
                (
                    "analytics_defaults",
                    models.JSONField(
                        default=dict, verbose_name="Analytics-Standardeinstellungen"
                    ),
                ),
                (
                    "scraper_settings",
                    models.JSONField(
                        default=dict, verbose_name="Scraper-Einstellungen"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Aktualisiert am"),
                ),
            ],
            options={
                "verbose_name": "Systemeinstellung",
                "verbose_name_plural": "Systemeinstellungen",
            },
        ),
    ]
