# Generated by Django 5.2.7 on 2025-10-17 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settingsapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="password_reset_token_expiry_hours",
            field=models.IntegerField(
                default=24, verbose_name="Passwort-Reset Token-Gültigkeit (Stunden)"
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="registration_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Erlaubt neuen Benutzern sich zu registrieren",
                verbose_name="Registrierung aktiviert",
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="require_email_verification",
            field=models.BooleanField(
                default=False,
                help_text="Neue Benutzer müssen ihre E-Mail-Adresse verifizieren",
                verbose_name="E-Mail-Verifizierung erforderlich",
            ),
        ),
    ]
