# Generated by Django 5.2.7 on 2025-10-19 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "settingsapp",
            "0002_systemsettings_password_reset_token_expiry_hours_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="developer_mode",
            field=models.BooleanField(
                default=False,
                help_text="Aktiviert den Developer Button systemweit für Administratoren",
                verbose_name="Developer Mode aktiviert",
            ),
        ),
    ]
