# Generated by Django 5.2.7 on 2025-10-19 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("settingsapp", "0003_add_developer_mode_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="systemsettings",
            name="developer_mode",
        ),
    ]
