# Generated by Django 5.2.7 on 2025-10-21 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settingsapp", "0004_remove_developer_mode_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="systemsettings",
            name="company_name",
            field=models.CharField(
                default="User Management System",
                max_length=100,
                verbose_name="Firmenname",
            ),
        ),
    ]
