# Generated by Django 5.2.7 on 2025-10-21 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settingsapp", "0005_remove_inventory_fields_safe"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="systemsettings",
            name="analytics_defaults",
        ),
        migrations.RemoveField(
            model_name="systemsettings",
            name="default_loss_factor_oil_percent",
        ),
        migrations.RemoveField(
            model_name="systemsettings",
            name="print_agent_url",
        ),
        migrations.RemoveField(
            model_name="systemsettings",
            name="qr_base_url",
        ),
        migrations.RemoveField(
            model_name="systemsettings",
            name="require_second_batch_scan_on_insufficient",
        ),
        migrations.RemoveField(
            model_name="systemsettings",
            name="scraper_settings",
        ),
        migrations.RemoveField(
            model_name="systemsettings",
            name="show_older_batch_warning",
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="account_lockout_duration_minutes",
            field=models.IntegerField(
                default=15, verbose_name="Account-Sperrung Dauer (Minuten)"
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="allow_multiple_sessions",
            field=models.BooleanField(
                default=True, verbose_name="Mehrere Sessions erlauben"
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="anonymize_old_data",
            field=models.BooleanField(
                default=True, verbose_name="Alte Daten anonymisieren"
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="api_key_expiry_days",
            field=models.IntegerField(
                default=365, verbose_name="API-Schlüssel Ablaufzeit (Tage)"
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="api_rate_limit_per_minute",
            field=models.IntegerField(
                default=100, verbose_name="API Rate Limit (pro Minute)"
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="audit_log_enabled",
            field=models.BooleanField(default=True, verbose_name="Audit-Log aktiviert"),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="backup_enabled",
            field=models.BooleanField(default=False, verbose_name="Backup aktiviert"),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="backup_frequency_hours",
            field=models.IntegerField(
                default=24, verbose_name="Backup-Häufigkeit (Stunden)"
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="backup_location",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="Backup-Speicherort"
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="backup_retention_days",
            field=models.IntegerField(
                default=30, verbose_name="Backup-Aufbewahrung (Tage)"
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="consent_required",
            field=models.BooleanField(
                default=True, verbose_name="Einverständnis erforderlich"
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="data_retention_days",
            field=models.IntegerField(
                default=2555, verbose_name="Daten-Aufbewahrung (Tage)"
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="default_user_role",
            field=models.CharField(
                default="VIEWER", max_length=20, verbose_name="Standard-Benutzerrolle"
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="email_enabled",
            field=models.BooleanField(
                default=False, verbose_name="E-Mail-Benachrichtigungen aktiviert"
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="email_from_address",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="E-Mail-Absender-Adresse"
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="external_api_timeout_seconds",
            field=models.IntegerField(
                default=30, verbose_name="Externe API-Timeout (Sekunden)"
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="force_password_change_on_first_login",
            field=models.BooleanField(
                default=True,
                verbose_name="Passwort-Änderung beim ersten Login erzwingen",
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="log_retention_days",
            field=models.IntegerField(
                default=90, verbose_name="Log-Aufbewahrung (Tage)"
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="maintenance_allowed_ips",
            field=models.JSONField(
                default=list,
                help_text="JSON-Array mit IP-Adressen die Zugriff haben",
                verbose_name="Erlaubte IP-Adressen im Wartungsmodus",
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="maintenance_message",
            field=models.TextField(
                default="Das System befindet sich im Wartungsmodus. Bitte versuchen Sie es später erneut.",
                verbose_name="Wartungsmodus-Nachricht",
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="maintenance_mode",
            field=models.BooleanField(
                default=False,
                help_text="Aktiviert den Wartungsmodus für das System",
                verbose_name="Wartungsmodus aktiviert",
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="max_login_attempts",
            field=models.IntegerField(
                default=5, verbose_name="Maximale Login-Versuche"
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="notify_on_failed_login",
            field=models.BooleanField(
                default=True, verbose_name="Bei fehlgeschlagenen Logins benachrichtigen"
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="notify_on_maintenance_mode",
            field=models.BooleanField(
                default=True, verbose_name="Bei Wartungsmodus benachrichtigen"
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="notify_on_system_errors",
            field=models.BooleanField(
                default=True, verbose_name="Bei System-Fehlern benachrichtigen"
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="notify_on_user_registration",
            field=models.BooleanField(
                default=True, verbose_name="Bei Benutzer-Registrierung benachrichtigen"
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="password_min_length",
            field=models.IntegerField(default=8, verbose_name="Mindestlänge Passwort"),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="password_require_special_chars",
            field=models.BooleanField(
                default=True, verbose_name="Sonderzeichen im Passwort erforderlich"
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="performance_monitoring",
            field=models.BooleanField(
                default=True, verbose_name="Performance-Monitoring aktiviert"
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="privacy_policy_url",
            field=models.URLField(blank=True, verbose_name="Datenschutz-URL"),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="retry_failed_requests",
            field=models.BooleanField(
                default=True, verbose_name="Fehlgeschlagene Requests wiederholen"
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="session_timeout_minutes",
            field=models.IntegerField(
                default=60, verbose_name="Session-Timeout (Minuten)"
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="smtp_host",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="SMTP-Host"
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="smtp_password",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="SMTP-Passwort"
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="smtp_port",
            field=models.IntegerField(default=587, verbose_name="SMTP-Port"),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="smtp_use_tls",
            field=models.BooleanField(default=True, verbose_name="SMTP TLS verwenden"),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="smtp_username",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="SMTP-Benutzername"
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="terms_of_service_url",
            field=models.URLField(blank=True, verbose_name="AGB-URL"),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="two_factor_required",
            field=models.BooleanField(
                default=False, verbose_name="Zwei-Faktor-Authentifizierung erforderlich"
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="user_registration_approval_required",
            field=models.BooleanField(
                default=False,
                verbose_name="Benutzer-Registrierung muss genehmigt werden",
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="user_session_timeout_minutes",
            field=models.IntegerField(
                default=480, verbose_name="Benutzer-Session-Timeout (Minuten)"
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="webhook_enabled",
            field=models.BooleanField(default=False, verbose_name="Webhooks aktiviert"),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="webhook_secret",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Webhook-Geheimnis"
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="webhook_url",
            field=models.URLField(blank=True, verbose_name="Webhook-URL"),
        ),
    ]
