# Generated by Django 5.0.8 on 2025-10-16 22:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("containers", "0001_initial"),
        ("fragrances", "0001_initial"),
        ("production", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stars",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Sterne",
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="Kommentar"),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Anzeigename",
                    ),
                ),
                (
                    "verified",
                    models.BooleanField(default=True, verbose_name="Verifiziert"),
                ),
                (
                    "is_public",
                    models.BooleanField(default=True, verbose_name="Öffentlich"),
                ),
                (
                    "moderated",
                    models.BooleanField(default=False, verbose_name="Moderiert"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am"),
                ),
                (
                    "container",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="containers.container",
                        verbose_name="Container",
                    ),
                ),
                (
                    "fragrance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fragrances.fragrance",
                        verbose_name="Duft",
                    ),
                ),
                (
                    "produced_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="production.produceditem",
                        verbose_name="Produzierter Artikel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bewertung",
                "verbose_name_plural": "Bewertungen",
                "ordering": ["-created_at"],
                "unique_together": {("produced_item",)},
            },
        ),
    ]
