# Generated by Django 5.0.8 on 2025-10-16 22:59

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("materials", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Container",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("PARFUM", "Parfum"),
                            ("ROOM_SPRAY", "Raumspray"),
                            ("COLONIA", "Kolonya"),
                            ("CAR_SPRAY", "Auto-Spray"),
                            ("OIL_PURE", "Reines Öl"),
                            ("ACCESSORY", "Zubehör"),
                        ],
                        max_length=20,
                        verbose_name="Typ",
                    ),
                ),
                (
                    "fill_volume_ml",
                    models.PositiveIntegerField(verbose_name="Füllvolumen (ml)"),
                ),
                (
                    "barcode",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Barcode"
                    ),
                ),
                (
                    "price_retail",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Verkaufspreis"
                    ),
                ),
                (
                    "loss_factor_oil_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("2.0"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0")),
                            django.core.validators.MaxValueValidator(Decimal("100.0")),
                        ],
                        verbose_name="Verlustfaktor Öl (%)",
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Aktiv")),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Gelöscht"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Gelöscht am"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Aktualisiert am"),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Gelöscht von",
                    ),
                ),
            ],
            options={
                "verbose_name": "Container",
                "verbose_name_plural": "Container",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notizen"),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Aktiv")),
                (
                    "container",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipes",
                        to="containers.container",
                        verbose_name="Container",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rezept",
                "verbose_name_plural": "Rezepte",
            },
        ),
        migrations.CreateModel(
            name="RecipeComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "component_kind",
                    models.CharField(
                        choices=[
                            ("PLACEHOLDER_OIL", "Platzhalter Öl"),
                            ("ALCOHOL", "Alkohol"),
                            ("WATER", "Wasser"),
                            ("FIXATEUR", "Fixateur"),
                            ("PACKAGING_BOTTLE", "Verpackung Flakon"),
                            ("PACKAGING_PART", "Verpackung Teil"),
                            ("PACKAGING_LABEL", "Verpackung Etikett"),
                            ("PACKAGING_BOX", "Verpackung Box"),
                            ("OTHER", "Sonstiges"),
                        ],
                        max_length=20,
                        verbose_name="Komponentenart",
                    ),
                ),
                (
                    "qty_required",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Benötigte Menge"
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[("ML", "Milliliter"), ("PCS", "Stück")],
                        max_length=10,
                        verbose_name="Einheit",
                    ),
                ),
                (
                    "is_optional",
                    models.BooleanField(default=False, verbose_name="Optional"),
                ),
                (
                    "material",
                    models.ForeignKey(
                        blank=True,
                        help_text="Nur für PLACEHOLDER_OIL null",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="materials.material",
                        verbose_name="Material",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="components",
                        to="containers.recipe",
                        verbose_name="Rezept",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rezept-Komponente",
                "verbose_name_plural": "Rezept-Komponenten",
            },
        ),
    ]
