# Generated by Django 5.0.8 on 2025-10-16 22:59

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("containers", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("fragrances", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Production",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "qty",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Menge",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Entwurf"),
                            ("READY", "Bereit"),
                            ("FAILED", "Fehlgeschlagen"),
                            ("DONE", "Abgeschlossen"),
                        ],
                        default="DRAFT",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "oil_cost_used",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=10,
                        verbose_name="Öl-Kosten verwendet",
                    ),
                ),
                (
                    "non_oil_cost_used",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=10,
                        verbose_name="Nicht-Öl-Kosten verwendet",
                    ),
                ),
                (
                    "total_production_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=10,
                        verbose_name="Gesamtproduktionskosten",
                    ),
                ),
                (
                    "loss_factor_oil_percent",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="Verlustfaktor Öl (%)",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Gestartet am"
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Beendet am"
                    ),
                ),
                (
                    "failure_reason",
                    models.TextField(blank=True, null=True, verbose_name="Fehlergrund"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am"),
                ),
                (
                    "container",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="containers.container",
                        verbose_name="Container",
                    ),
                ),
                (
                    "fragrance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fragrances.fragrance",
                        verbose_name="Duft",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Benutzer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Produktion",
                "verbose_name_plural": "Produktionen",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProducedItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("SOLD", "Verkauft")],
                        default="SOLD",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "unit_cost_snapshot",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Einzelkosten-Snapshot",
                    ),
                ),
                (
                    "price_at_sale",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Preis beim Verkauf",
                    ),
                ),
                ("serial", models.PositiveIntegerField(verbose_name="Seriennummer")),
                (
                    "uid",
                    models.CharField(max_length=20, unique=True, verbose_name="UID"),
                ),
                ("qr_code", models.URLField(verbose_name="QR-Code URL")),
                (
                    "produced_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Produziert am"
                    ),
                ),
                (
                    "sold_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Verkauft am"
                    ),
                ),
                (
                    "container",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="containers.container",
                        verbose_name="Container",
                    ),
                ),
                (
                    "fragrance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fragrances.fragrance",
                        verbose_name="Duft",
                    ),
                ),
                (
                    "production",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="produced_items",
                        to="production.production",
                        verbose_name="Produktion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Produzierter Artikel",
                "verbose_name_plural": "Produzierte Artikel",
                "ordering": ["-produced_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductionComponentUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "qty_used",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Verwendete Menge"
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[("ML", "Milliliter"), ("PCS", "Stück")],
                        max_length=10,
                        verbose_name="Einheit",
                    ),
                ),
                (
                    "before_stock",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Bestand vorher"
                    ),
                ),
                (
                    "after_stock",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Bestand nachher"
                    ),
                ),
                (
                    "unit_cost_at_use",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=10,
                        verbose_name="Einzelkosten bei Verwendung",
                    ),
                ),
                (
                    "cost_total_at_use",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Gesamtkosten bei Verwendung",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "production",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="component_usage",
                        to="production.production",
                        verbose_name="Produktion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Komponentenverbrauch",
                "verbose_name_plural": "Komponentenverbräuche",
            },
        ),
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qty", models.PositiveIntegerField(verbose_name="Menge")),
                (
                    "price_total",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Gesamtpreis"
                    ),
                ),
                (
                    "cost_total",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Gesamtkosten"
                    ),
                ),
                (
                    "profit_total",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Gesamtgewinn"
                    ),
                ),
                (
                    "sold_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Verkauft am"
                    ),
                ),
                (
                    "container",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="containers.container",
                        verbose_name="Container",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Erstellt von",
                    ),
                ),
            ],
            options={
                "verbose_name": "Verkauf",
                "verbose_name_plural": "Verkäufe",
                "ordering": ["-sold_at"],
            },
        ),
    ]
