# Generated by Django 5.0.8 on 2025-10-16 22:59

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("ALCOHOL", "Alkohol"),
                            ("FIXATEUR", "Fixateur"),
                            ("WATER", "Wasser"),
                            ("PACKAGING_BOTTLE", "Verpackung Flakon"),
                            ("PACKAGING_PART", "Verpackung Teil"),
                            ("PACKAGING_LABEL", "Verpackung Etikett"),
                            ("PACKAGING_BOX", "Verpackung Box"),
                            ("OTHER", "Sonstiges"),
                            ("TOOL", "Werkzeug"),
                        ],
                        max_length=20,
                        verbose_name="Kategorie",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[("ML", "Milliliter"), ("PCS", "Stück")],
                        max_length=10,
                        verbose_name="Einheit",
                    ),
                ),
                (
                    "stock_qty",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=10,
                        verbose_name="Bestand",
                    ),
                ),
                (
                    "min_qty",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=10,
                        verbose_name="Mindestbestand",
                    ),
                ),
                (
                    "cost_per_unit",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0"),
                        max_digits=10,
                        verbose_name="Kosten pro Einheit",
                    ),
                ),
                (
                    "sku_or_barcode",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="SKU/Barcode",
                    ),
                ),
                (
                    "is_tracked",
                    models.BooleanField(default=True, verbose_name="Wird verfolgt"),
                ),
                (
                    "cost_included",
                    models.BooleanField(default=True, verbose_name="Kosten enthalten"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Gelöscht"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Gelöscht am"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Aktualisiert am"),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Gelöscht von",
                    ),
                ),
            ],
            options={
                "verbose_name": "Material",
                "verbose_name_plural": "Materialien",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PackagingCompositionPart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "qty_per_parent",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Menge pro Hauptmaterial",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am"),
                ),
                (
                    "parent_material",
                    models.ForeignKey(
                        help_text="Material mit Kategorie PACKAGING_BOTTLE",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="composition_parts",
                        to="materials.material",
                        verbose_name="Hauptmaterial",
                    ),
                ),
                (
                    "part_material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="used_in_compositions",
                        to="materials.material",
                        verbose_name="Teil-Material",
                    ),
                ),
            ],
            options={
                "verbose_name": "Verpackungszusammensetzung",
                "verbose_name_plural": "Verpackungszusammensetzungen",
                "unique_together": {("parent_material", "part_material")},
            },
        ),
    ]
