# Generated by Django 5.0.8 on 2025-10-16 22:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("AUTH_LOGIN", "Anmeldung"),
                            ("AUTH_LOGOUT", "Abmeldung"),
                            ("AUTH_PASSKEY_REGISTER", "Passkey registriert"),
                            ("AUTH_PASSKEY_DELETE", "Passkey gelöscht"),
                            ("ORDER_RECEIVE", "Wareneingang"),
                            ("PRODUCT_ADJUST", "Produkt-Anpassung"),
                            ("MATERIAL_ADJUST", "Material-Anpassung"),
                            ("BATCH_ADJUSTMENT", "Charge-Anpassung"),
                            ("PRODUCTION_COMMIT", "Produktion bestätigt"),
                            ("SALE_COMMIT", "Verkauf bestätigt"),
                            ("TOOL_CHECKOUT", "Tool-Entnahme"),
                            ("LABEL_PRINT_JOB", "Etikettendruck"),
                            ("CRUD_CREATE", "Erstellt"),
                            ("CRUD_UPDATE", "Aktualisiert"),
                            ("CRUD_DELETE", "Gelöscht"),
                        ],
                        max_length=30,
                        verbose_name="Aktion",
                    ),
                ),
                (
                    "subject_type",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Objekttyp"
                    ),
                ),
                (
                    "subject_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Objekt-ID"
                    ),
                ),
                (
                    "payload_before",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Daten vorher"
                    ),
                ),
                (
                    "payload_after",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Daten nachher"
                    ),
                ),
                (
                    "ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP-Adresse"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, null=True, verbose_name="User-Agent"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am"),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Akteur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit-Log",
                "verbose_name_plural": "Audit-Logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["actor"], name="audit_audit_actor_i_17b775_idx"
                    ),
                    models.Index(
                        fields=["action"], name="audit_audit_action_86e815_idx"
                    ),
                    models.Index(
                        fields=["subject_type", "subject_id"],
                        name="audit_audit_subject_0ad3c9_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="audit_audit_created_2c1626_idx"
                    ),
                ],
            },
        ),
    ]
