# Generated by Django 5.2.7 on 2025-10-19 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Beschreibung"),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("AUTH_LOGIN", "Anmeldung"),
                    ("AUTH_LOGOUT", "Abmeldung"),
                    ("AUTH_PASSKEY_REGISTER", "Passkey registriert"),
                    ("AUTH_PASSKEY_DELETE", "Passkey gelöscht"),
                    ("ORDER_RECEIVE", "Wareneingang"),
                    ("PRODUCT_ADJUST", "Produkt-Anpassung"),
                    ("MATERIAL_ADJUST", "Material-Anpassung"),
                    ("BATCH_ADJUSTMENT", "Charge-Anpassung"),
                    ("PRODUCTION_COMMIT", "Produktion bestätigt"),
                    ("SALE_COMMIT", "Verkauf bestätigt"),
                    ("TOOL_CHECKOUT", "Tool-Entnahme"),
                    ("LABEL_PRINT_JOB", "Etikettendruck"),
                    ("CRUD_CREATE", "Erstellt"),
                    ("CRUD_UPDATE", "Aktualisiert"),
                    ("CRUD_DELETE", "Gelöscht"),
                    ("USER_SOFT_DELETE", "Benutzer Soft-Delete"),
                    ("USER_HARD_DELETE", "Benutzer Hard-Delete"),
                    ("USER_RESTORE", "Benutzer wiederhergestellt"),
                    ("USER_CREATE", "Benutzer erstellt"),
                    ("USER_UPDATE", "Benutzer aktualisiert"),
                    ("USER_STATUS_TOGGLE", "Benutzer-Status geändert"),
                ],
                max_length=30,
                verbose_name="Aktion",
            ),
        ),
    ]
